import test from "node:test";
import assert from "node:assert/strict";

import { load, parseAccount, parseDeployment, parseEnvFile, type ConfigIo } from "./config.ts";
import { isLauncherError } from "./errors.ts";

const ENV: NodeJS.ProcessEnv = { HOME: "/home/worker" };

const TEAM = "fdbdf01d-1111-4222-8333-444455556666";
const FILE = "0a1b2c3d-4444-4555-8666-777788889999";

/** The file provision-worker writes today, byte for byte in shape. */
const ACCOUNT_ENV = `# Generated by provision-worker. Holds a password and an MCP token.
PENPOT_ORIGIN="http://localhost:9001"
PENPOT_EMAIL="mcp-worker@example.test"
PENPOT_PASSWORD="hunter2 with spaces"
# Both ids are required: a workspace URL with only file-id renders an
# empty page. run-mcp-worker.py rewrites them per document.
PENPOT_FILE_URL="http://localhost:9001/#/workspace?team-id=${TEAM}&file-id=${FILE}"
PENPOT_MCP_URL="http://localhost:9001/mcp/stream?userToken=tok-abc123"
PENPOT_PROFILE_DIR="$HOME/.cache/penpot-headless/profile-mcp-worker"
`;

/** A ConfigIo over a plain map, which is all the layering rules need. */
function io(files: Record<string, string>): ConfigIo {
    return {
        read: (path) => files[path] ?? null,
        list: (dir) =>
            Object.keys(files)
                .filter((p) => p.startsWith(`${dir}/`) && !p.slice(dir.length + 1).includes("/"))
                .map((p) => p.slice(dir.length + 1)),
    };
}

function refusesConfig(fn: () => unknown): void {
    assert.throws(fn, (err: unknown) => isLauncherError(err) && err.code === "not-configured");
}

test("an account file parses into an address and its secrets", () => {
    const account = parseAccount("mcp-worker", ACCOUNT_ENV, ENV);

    assert.equal(account.name, "mcp-worker");
    assert.equal(account.origin, "http://localhost:9001");
    assert.equal(account.email, "mcp-worker@example.test");
    assert.equal(account.password, "hunter2 with spaces");
    assert.equal(account.mcpToken, "tok-abc123");
    assert.equal(account.profileDir, "/home/worker/.cache/penpot-headless/profile-mcp-worker");
    assert.deepEqual(account.defaultDocument, { teamId: TEAM, fileId: FILE });
});

test("a profile directory is derived when the file names none", () => {
    assert.equal(
        parseAccount("second", 'PENPOT_ORIGIN="http://localhost:9001"', ENV).profileDir,
        "/home/worker/.cache/penpot-headless/profile-second"
    );
});

test("an account with no scratch file is normal, not broken", () => {
    // provision-worker writes an empty file-id when it made no document.
    const text = `PENPOT_ORIGIN="http://localhost:9001"
PENPOT_FILE_URL="http://localhost:9001/#/workspace?team-id=${TEAM}&file-id="`;

    assert.equal(parseAccount("fresh", text, ENV).defaultDocument, undefined);
});

test("an account with no origin is refused, because nothing else can be inferred", () => {
    refusesConfig(() => parseAccount("broken", 'PENPOT_EMAIL="a@b.test"', ENV));
});

test("absent optional fields stay absent rather than becoming empty strings", () => {
    const account = parseAccount("bare", 'PENPOT_ORIGIN="http://localhost:9001"\nPENPOT_PASSWORD=""', ENV);

    assert.ok(!("password" in account));
    assert.ok(!("mcpToken" in account));
    assert.ok(!("defaultDocument" in account));
});

test("env files parse the way a shell would source them", () => {
    const vars = parseEnvFile(
        [
            "# a comment",
            "   # an indented comment",
            "",
            "export EXPORTED=one",
            'QUOTED="two"',
            "LITERAL='$HOME stays'",
            'EXPANDED="$HOME/x"',
            'BRACED="${HOME}/y"',
            "BARE=three # trailing comment",
            'UNSET_VAR="[$NOT_SET]"',
            "NOT A PAIR",
            "=novalue",
        ].join("\n"),
        ENV
    );

    assert.equal(vars.get("EXPORTED"), "one");
    assert.equal(vars.get("QUOTED"), "two");
    assert.equal(vars.get("LITERAL"), "$HOME stays");
    assert.equal(vars.get("EXPANDED"), "/home/worker/x");
    assert.equal(vars.get("BRACED"), "/home/worker/y");
    assert.equal(vars.get("BARE"), "three");
    assert.equal(vars.get("UNSET_VAR"), "[]");
    assert.ok(!vars.has("NOT A PAIR"));
    assert.ok(!vars.has(""));
});

test("a compose deployment maps onto the nested shape", () => {
    const json = `{ "backend": "compose", "projectDir": "../../deploy/home-cluster",
                    "service": "penpot-mcp", "portRange": [4601, 4608] }`;
    const d = parseDeployment(json, "/etc/headless");

    assert.equal(d.backend, "compose");
    assert.deepEqual(d.portRange, { lo: 4601, hi: 4608 });
    assert.deepEqual(d.compose, { projectDir: "../../deploy/home-cluster", service: "penpot-mcp" });
    assert.equal(d.configDir, "/etc/headless");
    assert.equal(d.kubectl, undefined);
});

test("exposure defaults to none, because the deployments that matter satisfy it", () => {
    const json = `{ "backend": "compose", "projectDir": ".", "service": "penpot-mcp", "portRange": [4601, 4608] }`;

    assert.equal(parseDeployment(json, "/etc").exposure, "none");
});

test("a kubectl deployment takes its range under the local name", () => {
    const json = `{ "backend": "kubectl", "context": "home", "namespace": "penpot",
                    "selector": "app=penpot-mcp", "localPortRange": [4601, 4608],
                    "exposure": "port-forward" }`;
    const d = parseDeployment(json, "/etc");

    assert.equal(d.backend, "kubectl");
    assert.equal(d.exposure, "port-forward");
    assert.deepEqual(d.portRange, { lo: 4601, hi: 4608 });
    assert.deepEqual(d.kubectl, { namespace: "penpot", selector: "app=penpot-mcp", context: "home" });
    assert.equal(d.compose, undefined);
});

test("an absent kubectl context stays absent", () => {
    const json = `{ "backend": "kubectl", "namespace": "penpot", "selector": "a=b", "localPortRange": [1, 2] }`;

    assert.ok(!("context" in parseDeployment(json, "/etc").kubectl!));
});

test("a malformed deployment names what is wrong", () => {
    refusesConfig(() => parseDeployment("not json", "/etc"));
    refusesConfig(() => parseDeployment("[]", "/etc"));
    refusesConfig(() => parseDeployment(`{ "backend": "podman", "portRange": [1, 2] }`, "/etc"));
    refusesConfig(() => parseDeployment(`{ "backend": "compose", "service": "m", "portRange": [1, 2] }`, "/etc"));
    refusesConfig(() => parseDeployment(`{ "backend": "compose", "projectDir": ".", "service": "m" }`, "/etc"));
    refusesConfig(() =>
        parseDeployment(`{ "backend": "compose", "projectDir": ".", "service": "m", "portRange": [1] }`, "/etc")
    );
    refusesConfig(() =>
        parseDeployment(`{ "backend": "compose", "projectDir": ".", "service": "m", "portRange": ["a", "b"] }`, "/etc")
    );
    refusesConfig(() =>
        parseDeployment(
            `{ "backend": "compose", "projectDir": ".", "service": "m", "portRange": [1, 2], "exposure": "tunnel" }`,
            "/etc"
        )
    );
});

test("load reads the deployment and every account beside it", () => {
    const settings = load(
        "/etc/headless",
        ENV,
        io({
            "/etc/headless/deployment.json": `{ "backend": "compose", "projectDir": "..",
                                                "service": "penpot-mcp", "portRange": [4601, 4608] }`,
            "/etc/headless/accounts/mcp-worker.env": ACCOUNT_ENV,
            "/etc/headless/accounts/second.env": 'PENPOT_ORIGIN="https://design.penpot.app"',
            "/etc/headless/accounts/README.md": "not an account",
            "/etc/headless/accounts/nested/deeper.env": 'PENPOT_ORIGIN="http://nope"',
        })
    );

    assert.deepEqual([...settings.accounts.keys()].sort(), ["mcp-worker", "second"]);
    assert.equal(settings.accounts.get("second")?.origin, "https://design.penpot.app");
    assert.equal(settings.deployment?.backend, "compose");
});

test("no deployment file means exec is unavailable, not that anything is broken", () => {
    const settings = load("/etc/headless", ENV, io({ "/etc/headless/accounts/w.env": ACCOUNT_ENV }));

    assert.equal(settings.deployment, undefined);
    assert.equal(settings.accounts.size, 1);
});

test("an empty configuration directory loads to nothing at all", () => {
    const settings = load("/etc/headless", ENV, io({}));

    assert.equal(settings.deployment, undefined);
    assert.equal(settings.accounts.size, 0);
});
